<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos
[
<!ELEMENT pedidos (sucursal+)>
<!ELEMENT sucursal (direccion+, nombreTrabajador, fechaPedido, observaciones, articulo+)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombreTrabajador (#PCDATA)>
<!ELEMENT fechaPedido (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulo (numUnidades, precioUnidad, observaciones, plazoRevision)>
<!ATTLIST articulo codigo CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numUnidades (#PCDATA)>
<!ELEMENT precioUnidad (#PCDATA)>
<!ELEMENT plazoRevision (#PCDATA)>
]
>

<pedidos>
    <sucursal codigo="A0000001">
        <direccion>Calle Ecuador NÂº7</direccion>
        <nombreTrabajador>Eustaquio Lara Lozano</nombreTrabajador>
        <fechaPedido>2023-02-10</fechaPedido>
        <observaciones>urgente</observaciones>
        <articulo codigo="AAA-001">
            <numUnidades>1</numUnidades>
            <precioUnidad>32</precioUnidad>
            <observaciones>Muy pesado</observaciones>
            <plazoRevision>15</plazoRevision>
        </articulo>
    </sucursal>
</pedidos>